Next fixes
marrow/mailer pull request #98
Opened 2021-08-14 16:28 UTC by homeworkprod

Hey Alice, I finally managed to get a deeper go at the `next` branch (on Python 3.9, to which I just upgraded).

I came across a few errors right away for which I have provided what I think should be fixes (unless I misinterpreted your intention behind the code pieces in question).

Let me know what you think. :)

2022-02-17 20:19 UTC, amcgregor commented
I'll have a gander at this shortly. Apologies for the insane delay.

2022-02-17 20:42 UTC, amcgregor requested changes, later dismissed
I only request that you revert the generator/list comprehension change, otherwise thank you so very much for contributing! Once again, my deepest apologies for taking so long to get to this. It's been… a crazy time, shall we say.

2022-02-17 20:42 UTC, amcgregor commented on marrow/mailer/address.py
> +		return f"AddressList(\"{', '.join(str(i) for i in self)}\")"
A ha, no, the original comprehension was actually correct! 😁 Good catch on the missing parenthesis, though; that's my bad. What you've replaced it with is a list comprehension, which, while still functional, stops and then creates a concrete list from the result of a generator comprehension adding the memory overhead of a true list to each evaluation. The original was the bare [generator expression](https://docs.python.org/3.9/glossary.html#index-20). Join accepts ["iterable objects"](https://docs.python.org/3/library/stdtypes.html#str.join), which both lists and generators qualify as.

2022-02-18 14:59 UTC, homeworkprod commented on marrow/mailer/address.py
> +		return f"AddressList(\"{', '.join(str(i) for i in self)}\")"
Hey,

> What you've replaced it with is a list comprehension

are you sure? I believe it *was* a list comprehension `[… for …]`, and I have removed the square brackets to turn it into a more efficient generator expression.

2022-02-18 15:15 UTC, homeworkprod commented
It seems to me you've applied pretty much these changes (including the LC → GE change) in 46b1c20a6672d51b9a9cf008aa4a581b1928903d already anyway.

2022-02-18 17:19 UTC, amcgregor commented on marrow/mailer/address.py
> +		return f"AddressList(\"{', '.join(str(i) for i in self)}\")"
Yup, nope, my dyslexia got the best of me here. 🙇 Apologies. Sometimes, to go faster, I need to slow down.

2022-02-18 17:24 UTC, amcgregor commented
Closing as already implemented. Temporary variable use instead of just switching which quotes were in use (d'oh!) but still effective.

2022-02-18 17:24 UTC, closed without merging